services:
  web:
    container_name: web
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./modx:/var/www/html/
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default-dev.conf
    restart: always
    environment:
      VIRTUAL_HOST: russoft-it.ru
      LETSENCRYPT_HOST: russoft-it.ru
      LETSENCRYPT_EMAIL: rewbed@gmail.com
      VIRTUAL_PORT: 80 # Указываем порт, на котором работает сервис в рамках сети докера
    networks:
      - proxy-net-v1
  db:
    container_name: db
    image: mariadb
    restart: always
    command: --init-file /data/application/init.sql
    volumes:
      - ./docker/mariadb/init.sql:/data/application/init.sql
      - ./docker/mariadb/db:/var/lib/mysql
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: modx
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    networks:
      - proxy-net-v1

networks:
  proxy-net-v1:
    driver: bridge
    name: proxy-net-v1
