services:
  portainer:
    image: image
    restart: always
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy-net-v1

networks:
  proxy-net-v1:
    driver: bridge
    name: proxy-net-v1
